obj-y += fastboot.o command.o
obj-y += cmd_version.o
obj-$(CONFIG_FASTBOOT_HELP_COMMAND) += cmd_help.o
obj-$(CONFIG_FASTBOOT_MEM_COMMAND) += cmd_mem.o
obj-$(CONFIG_ENVIRONMENT_SUPPORT) += cmd_env.o
obj-$(CONFIG_IDMELIB_SUPPORT) += cmd_idme.o
