obj-y += libc/string.o
obj-y += debug/debug.o
obj-$(CONFIG_FRAMEBUFFER_SUPPORT) += framebuffer/
obj-y += common.o bootmode.o fastboot.o
obj-$(CONFIG_THREAD_SUPPORT) += thread.o
obj-$(CONFIG_LIBSEJ_SUPPORT) += libsej/
obj-$(CONFIG_ENVIRONMENT_SUPPORT) += environment.o
obj-$(CONFIG_SPOOF_SUPPORT) += spoof/