//
// SPDX-FileCopyrightText: 2026 Ben Grisdale <bengris32@protonmail.ch>
// SPDX-License-Identifier: AGPL-3.0-or-later
//

#pragma once

#define BOARD_NAME          "Echo Input"
#define RECOVERY_PARTITION  "swdl"

#define HAVE_EARLY_INIT
#define HAVE_FASTBOOT_INIT
#define HAVE_FASTBOOT_CMD_REBOOT

#define MDELAY_FUNC_ADDR                  0x41E11650

#define FB_CMD_FLASH_FUNC_ADDR            0x41E1E3E1
#define FB_CMD_ERASE_FUNC_ADDR            0x41E1E529
#define FB_CMD_REBOOT_FUNC_ADDR           0x41E1D555
#define FB_CMD_REBOOT_RECOVERY_FUNC_ADDR  0x41E1D431

#define FB_FLASH_CMD_REGISTER_CALLER      0x41E1CF46
#define FB_ERASE_CMD_REGISTER_CALLER      0x41E1CF5A
#define FB_REBOOT_CMD_REGISTER_CALLER     0x41E1CF84
#define FB_REBOOT_BL_CMD_REGISTER_CALLER  0x41E1CF98
#define FB_SET_ACTIVE_CMD_REGISTER_CALLER 0x41E1D042

#define FB_INIT_LOG_FUNC_CALLER_ADDR      0x41E1CEA0

#define GET_BOOT_PART_FUNC_ADDR           0x41E18638
#define GET_BOOT_PART_FUNC_CALLER_ADDR    0x41E1BFD2
#define GET_ACTIVE_SLOT_FUNC_CALLER_ADDR  0x41E1BFCC

#define UNLOCK_CHECK_FUNC_ADDR            0x41E0196C
#define SELINUX_CMDLINE_FUNC_ADDR         0x41E1BF2C
#define VERITY_CMDLINE_FUNC_ADDR          0x41E1D2C4
#define CMDLINE_APPEND_FUNC_ADDR          0x41E1AAE0

#define LP5562_WRITE_FUNC_ADDR            0x41E1A91C
#define FB_LED_GREEN_FUNC_CALLER_ADDR     0x41E0DF22
